#' r/geo — Bundled administrative-boundary metadata
#'
#' Loads the lightweight per-level metadata (id, name, admin_level, and
#' parent-linkage columns) generated by `data-raw/generate_geo.R`. The full
#' geometry stays in `assets/geo/*.geojson` (countries) and per-country files
#' under `assets/geo/{states,counties}/`; the maplibre widget fetches them
#' lazily in the browser — the R side only needs names and keys to populate
#' the pickers and to filter children by their selected parents.
#'
#' The data is loaded once per process and cached; sessions share it.
#'
#' @md
#' @name geo
box::use(
  jsonlite[fromJSON],
)

.geo_cache <- new.env(parent = emptyenv())

#' Load the three admin-level metadata tables
#'
#' Reads `assets/geo/{countries,states,counties}_meta.json` and returns them
#' as data.frames. Cached in `.geo_cache` after the first call.
#'
#' @return A list with `countries`, `states`, and `counties` data.frames.
#'   Common columns: `id`, `name`, `admin_level`. `states` additionally has
#'   `country_id` / `country_name`; `counties` has `country_id`.
#' @export
load_geo <- function() {
  if (is.null(.geo_cache$data)) {
    read_meta <- function(file) {
      jsonlite::fromJSON(file.path("assets", "geo", file), simplifyVector = TRUE)
    }
    .geo_cache$data <- list(
      countries = read_meta("countries_meta.json"),
      states    = read_meta("states_meta.json"),
      counties  = read_meta("counties_meta.json")
    )
  }
  .geo_cache$data
}

#' Build an id → name lookup for a metadata table
#'
#' @param meta A data.frame with `id` and `name` columns.
#' @return A named character vector (`id` = `name`).
#' @export
lookup_names <- function(meta) {
  stats::setNames(meta$name, meta$id)
}

#' Filter a child table to rows whose `country_id` is in `country_ids`
#'
#' @param meta A data.frame with a `country_id` column.
#' @param country_ids Character vector of selected country ids.
#' @return The filtered data.frame (row order preserved).
#' @export
filter_by_country <- function(meta, country_ids) {
  if (length(country_ids) == 0L) {
    return(meta[0, , drop = FALSE])
  }
  meta[meta$country_id %in% country_ids, , drop = FALSE]
}
