-- ────────────────────────────────────────────────────────────────
-- Database schema for the compose example project
-- ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
    id          SERIAL PRIMARY KEY,
    username    VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,             -- bcrypt $2b$ hash
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Seed a demo user (password: "demo123")
-- The hash below is a bcrypt hash of "demo123" generated by R's bcrypt
-- package (\$2a$ prefix). Node.js and other bcrypt implementations can
-- verify against it; see modules/logic/db/users.r check_password() for
-- cross-prefix handling.
INSERT INTO users (username, password_hash)
VALUES ('demo', '$2a$12$2cdsNtnGoxXFTV5YJxGmdu9ITeDN4yqlac0jCUttQWKTf5G8HPhhK')
ON CONFLICT (username) DO NOTHING;
